[ai_detection]
API_USER = "952331767"
API_SECRET = "Z5tmvY5owM54Bwyx7wTvw9e9RwSD4oQy"
endpoint   = "https://api.sightengine.com/1.0/check.json"
models     = "genai"

[nightshade]
# Gelecekte CLI yolu veya model ağırlıkları
bin_path = "/usr/local/bin/nightshade"
