[ai_detection]
API_USER = "1298675546"
API_SECRET = "nkreuPfLDNE7yAAeYqfdBFwDLgEGij85"
endpoint   = "https://api.sightengine.com/1.0/check.json"
models     = "ai-generated"

[nightshade]
# Gelecekte CLI yolu veya model ağırlıkları
bin_path = "/usr/local/bin/nightshade"
